### ISSUE TITLE
TODO/FIXME Count 7

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/minimal-cipher#18]
- [ ] TODO: ensure this polyfill is necessary
       Commit: (937b290) Use web streams ponyfill if necessary.
       File:  [util-browser.js:9](https://github.com/digitalbazaar/minimal-cipher/blob/master/util-browser.js#L9)
       Dave Longley commented a year ago

  - [ ] TODO: consider accepting JWK format for `staticPublicKey` not just LD key
       Commit: (c6899ee) Check key type.
       File:  [algorithms/x25519.js:72](https://github.com/digitalbazaar/minimal-cipher/blob/master/algorithms/x25519.js#L72)
       Dave Longley commented a year ago

  - [ ] FIXME: not FIPs compliant yet; replace!
       Commit: (f26a2a4) Add X25519 ECDH support.
       File:  [algorithms/fips.js:7](https://github.com/digitalbazaar/minimal-cipher/blob/master/algorithms/fips.js#L7)
       Dave Longley commented a year ago

  - [ ] TODO: Describe the required KEK API:
       Commit: (5428a7f) Add core files.
       File:  [README.md:168](https://github.com/digitalbazaar/minimal-cipher/blob/master/README.md#L168)
       Dave Longley commented a year ago

  - [ ] TODO: Implement this
       Commit: (a4a1ee5) Expand README, add usage docs.
       File:  [README.md:139](https://github.com/digitalbazaar/minimal-cipher/blob/master/README.md#L139)
       Dmitri Zagidulin commented 10 months ago

  - [ ] APIs, including Web KMS (TODO: citation needed).
       Commit: (5428a7f) Add core files.
       File:  [README.md:41](https://github.com/digitalbazaar/minimal-cipher/blob/master/README.md#L41)
       Dave Longley commented a year ago

  - [ ] TODO: consider a cache of encrypted_key => CEKs to reduce unwrapping
       Commit: (4efdf85) Add TODO.
       File:  [DecryptTransformer.js:108](https://github.com/digitalbazaar/minimal-cipher/blob/master/DecryptTransformer.js#L108)

**Comment by JSAssassin** [comment]
Closing, opened individual issues for the items on the list.
